apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nats
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: nats
      version: '4.0.x'
      sourceRef:
        kind: HelmRepository
        name: nats
        namespace: flux-system
      interval: 1m